- name: add microsoft apt key
  become: yes
  apt_key:
    state: present
    url: https://packages.microsoft.com/keys/microsoft.asc

- name: add repository
  become: yes
  apt_repository:
    repo: "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main"
    state: present

- name: update apt cache
  become: yes
  apt:
    update_cache: yes
