- include_tasks: "{{ ansible_distribution }}.yml"

# - name: get addon download link
#   shell: wget $(echo -e $(curl -s {{ item.url }} | grep -o 'https[^"]*xpi')) --output-document=/tmp/{{ item.id }}
#   args:
#     executable: /bin/bash
#   with_items: "{{ addons }}"
#   delegate_to: localhost

# - name: installing /tmp/{{ item.id }}.xpi
#   become: yes
#   copy:
#     src: /tmp/{{ item[0].id }}.xpi
#     dest: "{{ item[1] }}"
#   with_items:
#     - "{{ addons }}"
#     -
#       - /usr/lib/mozilla/extensions/
#       - /usr/lib64/mozilla/extensions/
#       - /usr/share/mozilla/extensions/
#   ignore_errors: yes

#   - name: cleanup
#     file:
#       path: "{{ item }}"
#       state: absent
#     loop:
#       - /tmp/{{ item.id }}.xpi

#   with_items: "{{ addons }}"