- name: add oracle key
  become: yes
  apt_key:
    url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
    state: present

- name: add repositories
  become: yes
  apt_repository:
      repo: "{{ item }}"
      state: present
  with_items:
    - "deb [arch=amd64] http://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release }} contrib non-free"
  register: vbox_ubuntu_repo_added
  ignore_errors: yes

- name: add repositories
  become: yes
  apt_repository:
      repo: "{{ item }}"
      state: present
  with_items:
    - "deb [arch=amd64] http://download.virtualbox.org/virtualbox/debian focal contrib non-free"
  when: vbox_ubuntu_repo_added is failed

- name: update apt cache
  become: yes
  apt:
    update_cache: yes