- name: install virtualbox dependencies
  become: yes
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - binutils
    - gcc
    - make
    - patch
    - libgomp
    - glibc-headers
    - glibc-devel
    - kernel-headers
    - kernel-devel
    - dkms
    - qt5-qtx11extras
    - libxkbcommon
    - vagrant
    - VirtualBox-6.0
