- include_tasks: "{{ ansible_pkg_mgr }}.yml"

- include_tasks: "{{ ansible_distribution }}.yml"

- name: add user to vbox group
  become: yes
  user:
    name: "{{ ansible_user }}"
    groups: vboxusers
    append: yes
