- include_tasks: "{{ ansible_pkg_mgr }}.yml"

- name: install virtualbox dependencies
  become: yes
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - binutils
    - gcc
    - make
    - patch
    - libgomp
    - glibc-headers
    - glibc-devel
    - kernel-headers
    - kernel-devel
    - dkms
    - qt5-qtx11extras
    - libxkbcommon
    - vagrant
    - VirtualBox-6.0
  when:
    - ansible_distribution == "Fedora"

- name: install virtualbox-6.0
  become: yes
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - vagrant
    - virtualbox-6.0
  when:
    - ansible_distribution == "Debian"

- name: install virtualbox-6.1
  become: yes
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - vagrant
    - virtualbox-6.1
  when:
    - ansible_distribution == "Ubuntu"

- name: add user to vbox group
  become: yes
  user:
    name: "{{ ansible_user }}"
    groups: vboxusers
    append: yes
