- name: get franz link
  shell: |
    curl -s $( \
      curl -si https://github.com/meetfranz/franz/releases/latest \
      | grep Location \
      | awk '{print $2}' \
      | tr -dc '[[:print:]]' \
    ) \
    | grep download \
    | grep 'href=".*\.deb"' \
    | sed 's|^.*href="||' \
    | sed 's|".*$||'
  register: franz_link
  delegate_to: localhost

- name: "Install https://github.com{{ franz_link.stdout }}"
  become: yes
  apt:
    deb: "https://github.com{{ franz_link.stdout }}"