- name: get displaylink latest release link
  shell: |
    curl -s $( \
      curl -si https://github.com/displaylink-rpm/displaylink-rpm/releases/latest \
      | grep Location \
      | awk '{print $2}' \
      | tr -dc '[[:print:]]' \
    ) \
    | grep 'href=".*fedora-{{ ansible_distribution_major_version }}.*{{ ansible_architecture }}\.rpm' \
    | sed 's|^.*href="||' \
    | sed 's|".*$||'
  register: displaylink_dl_link
  delegate_to: localhost

- name: download displaylink driver
  get_url: 
    url: "https://github.com{{ displaylink_dl_link.stdout }}"
    dest: /tmp/
  register: displaylink_filename

- name: install displaylink driver
  become: yes
  yum:
    name: "{{ displaylink_filename.dest }}"
    state: present

- name: delete displaylink driver rpm
  file:
    path: "{{ displaylink_filename.dest }}"
    state: absent

- name: enable & restart displaylink service
  become: yes
  service:
    name: displaylink
    enabled: yes
    state: restarted