- name: update apt cache
  become: yes
  apt:
    update_cache: yes
  
- name: apt state latest
  become: yes
  apt:
    name: "*"
    state: latest
  register: upgrade_apt
  ignore_errors: yes

- name: apt-get dist-upgrade
  become: yes
  apt:
    upgrade: dist
  register: upgrade_dist
  ignore_errors: yes

#- fail:
#    msg: "Both apt upgrade methods failed"
#  when: upgrade_apt.rc != 0 and upgrade_dist.rc != 0
