- name: "perform Ubuntu tasks"
  block:

  - name: add repositories
    become: yes
    apt_repository:
      repo: "{{ item }}"
      state: present
    with_items:
      - "deb http://archive.ubuntu.com/ubuntu {{ ansible_distribution_release }} main restricted universe multiverse"
      - "deb http://archive.ubuntu.com/ubuntu {{ ansible_distribution_release }}-updates main restricted universe multiverse"
      - "deb http://archive.ubuntu.com/ubuntu {{ ansible_distribution_release }}-backports main restricted universe multiverse"
      - "deb http://archive.canonical.com/ubuntu {{ ansible_distribution_release }} partner"
      - "deb http://security.ubuntu.com/ubuntu {{ ansible_distribution_release }}-security main restricted universe multiverse"
