- name: "perform Ubuntu tasks"
  block:

  - name: add repositories
    become: yes
    apt_repository:
      repo: "{{ item }}"
      state: present
      update_cache: yes
    with_items:
      - "deb http://de.archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }} main restricted"
      - "deb http://de.archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }}-updates main restricted"
      - "deb http://de.archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }} universe"
      - "deb http://de.archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }}-updates universe"
      - "deb http://de.archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }} multiverse"
      - "deb http://de.archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }}-updates multiverse"
      - "deb http://de.archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }}-backports main restricted universe multiverse"
      - "deb http://archive.canonical.com/ubuntu {{ ansible_distribution_release }} partner"
      - "deb http://security.ubuntu.com/ubuntu {{ ansible_distribution_release }}-security main restricted"
      - "deb http://security.ubuntu.com/ubuntu {{ ansible_distribution_release }}-security universe"
      - "deb http://security.ubuntu.com/ubuntu {{ ansible_distribution_release }}-security multiverse"
