- name: "perform Ubuntu tasks"
  block:

  - name: add repositories
    become: yes
    apt_repository:
      repo: "{{ item }}"
      state: present
    with_items:
      - "deb http://archive.ubuntu.com/ubuntu {{ ansible_distribution_release }} main restricted universe multiverse partner"

