- name: install prerequisites
  become: yes
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg2
    - software-properties-common

- name: add docker apt key
  become: yes
  apt_key:
    state: present
    url: https://download.docker.com/linux/ubuntu/gpg

- name: add docker repo
  become: yes
  shell: echo "deb [arch=amd64] https://download.docker.com/linux/ubuntu `lsb_release -cs` stable" > /etc/apt/sources.list.d/docker.list

- name: update apt cache
  become: yes
  apt:
    update_cache: yes

- name: install software
  become: yes
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - docker-ce
    - docker-ce-cli
    - containerd.io