- name: install snap
  become: yes
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - snapd

- name: install 
  become: yes
  snap:
    name: insomnia
    state: present

# - name: install insomnia
#   become: yes
#   command: snap install insomnia