- include_tasks: "{{ ansible_pkg_mgr }}.yml"

- name: copy certificates
  become: yes
  copy:
    src: files/certificates/
    dest: /etc/ssl/certs
    mode: a+r

- name: link certificates
  become: yes
  shell: "for i in /etc/ssl/certs/*; do ln -s $i /opt/Citrix/ICAClient/keystore/cacerts/$(echo $i | sed 's|^.*/||'); done"

- name: rehash certificates
  become: yes
  shell: c_rehash /opt/Citrix/ICAClient/keystore/cacerts/