- include_tasks: "{{ ansible_pkg_mgr }}.yml"

- name: install
  become: true
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - python-lxml
    - python3-lxml
    - syncthing

- name: copy config files
  copy:
    src: "{{ item }}"
    dest: ~/.config/syncthing
    force: no
  with_items:
    - "{{ inventory_hostname }}/cert.pem"
    - "{{ inventory_hostname }}/config.xml"
    - "{{ inventory_hostname }}/https-cert.pem"
    - "{{ inventory_hostname }}/https-key.pem"
    - "{{ inventory_hostname }}/key.pem"
  ignore_errors: yes
  register: copied_syncthing_config

# weird: ansible_user does not work after updating to 2.8
- name: whoami
  command: whoami
  register: whoami
  changed_when: no

- name: configure values in config.xml
  xml:
    path: ~/.config/syncthing/config.xml
    xpath: "{{ item.xpath }}"
    value: "{{ item.value }}"
  with_items:
    - { xpath: "/configuration/gui/address", value: "0.0.0.0:8384" }
    - { xpath: "/configuration/gui/user", value: "{{ whoami.stdout }}" } # weird: ansible_user does not work after updating to 2.8
    - { xpath: "/configuration/gui/theme", value: "dark" }
    - { xpath: "/configuration/options/startBrowser", value: "false" }
    - { xpath: "/configuration/options/natEnabled", value: "true" }
    - { xpath: "/configuration/options/restartOnWakeup", value: "true" }
    - { xpath: "/configuration/options/upgradeToPreReleases", value: "false" }
    - { xpath: "/configuration/options/cacheIgnoredFiles", value: "false" }
    - { xpath: "/configuration/options/limitBandwidthInLan", value: "false" }
    - { xpath: "/configuration/options/minHomeDiskFree", value: "1" }
    - { xpath: "/configuration/options/overwriteRemoteDeviceNamesOnConnect", value: "false" }

- name: configure attributes in config.xml
  xml:
    path: ~/.config/syncthing/config.xml
    xpath: "{{ item.xpath }}"
    attribute: "{{ item.attribute }}"
    value: "{{ item.value }}"
  with_items:
    - { xpath: "/configuration/gui", attribute: "debugging", value: "false" }
    - { xpath: "/configuration/gui", attribute: "tls", value: "true" }
    - { xpath: "/configuration/gui", attribute: "enabled", value: "true" }
    - { xpath: "/configuration/options/minHomeDiskFree", attribute: "unit", value: "%" }

- name: copy service file
  become: yes
  copy:
    src: syncthing@.service
    dest: /lib/systemd/system/syncthing@.service
    force: no
    mode: a+r

- name: configure & start service
  become: yes
  systemd:
    name: "syncthing@{{ ansible_user }}.service"
    daemon_reload: yes
    enabled: yes
    state: started